# Generated by Django 5.2.1 on 2025-05-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
        ("users", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dietary_preferences",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_with_preference",
                to="recipes.dietarypreferencetag",
                verbose_name="饮食偏好",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="disliked_ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_disliking",
                to="recipes.ingredient",
                verbose_name="不吃的食材",
            ),
        ),
    ]
