# Generated by Django 5.2.1 on 2025-06-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_remove_recipe_main_image_url_recipe_main_image"),
        ("users", "0004_shoppinglistitem_userinventoryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_recipes",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="recipes.recipe",
                verbose_name="收藏的菜谱",
            ),
        ),
    ]
