# Generated by Django 5.2.1 on 2025-05-12 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryPreferenceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="饮食偏好标签名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "饮食偏好标签",
                "verbose_name_plural": "饮食偏好标签",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="食材名称"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vegetable", "蔬菜"),
                            ("meat", "肉类"),
                            ("poultry", "禽类"),
                            ("seafood", "海鲜"),
                            ("dairy", "乳制品"),
                            ("fruit", "水果"),
                            ("grain", "谷物/主食"),
                            ("spice", "香料/调料"),
                            ("herb", "香草"),
                            ("oil", "油类"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="分类",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="图片链接"),
                ),
                (
                    "common_substitutes",
                    models.ManyToManyField(
                        blank=True, to="recipes.ingredient", verbose_name="常见替代品"
                    ),
                ),
            ],
            options={
                "verbose_name": "食材",
                "verbose_name_plural": "食材",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="菜谱标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="简介"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cooking_time_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="烹饪时长(分钟)"
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "简单"), (2, "中等"), (3, "困难")],
                        null=True,
                        verbose_name="难度",
                    ),
                ),
                (
                    "main_image_url",
                    models.URLField(blank=True, null=True, verbose_name="主图链接"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending_review", "待审核"),
                            ("published", "已发布"),
                            ("rejected", "已拒绝"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="菜系"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "dietary_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipes",
                        to="recipes.dietarypreferencetag",
                        verbose_name="饮食标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜谱",
                "verbose_name_plural": "菜谱",
                "ordering": ["-updated_at", "title"],
            },
        ),
    ]
