# Generated by Django 5.2.1 on 2025-05-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(verbose_name="用量")),
                (
                    "unit",
                    models.CharField(
                        help_text="例如：克, 个, 勺, 毫升, 杯",
                        max_length=50,
                        verbose_name="单位",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="例如：切碎, 去籽, 融化",
                        max_length=255,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                        verbose_name="食材",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.recipe",
                        verbose_name="菜谱",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜谱食材",
                "verbose_name_plural": "菜谱食材",
                "ordering": ["recipe", "id"],
                "unique_together": {("recipe", "ingredient")},
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes_using_ingredient",
                through="recipes.RecipeIngredient",
                through_fields=("recipe", "ingredient"),
                to="recipes.ingredient",
                verbose_name="所需食材",
            ),
        ),
    ]
