# Generated by Django 5.2.1 on 2025-05-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vegetable", "蔬菜"),
                    ("fruit", "水果"),
                    ("meat", "肉类"),
                    ("poultry", "禽类"),
                    ("seafood", "海鲜"),
                    ("egg", "蛋类"),
                    ("dairy", "乳制品"),
                    ("mushroom", "菌菇"),
                    ("legume", "豆类"),
                    ("nut_seed", "坚果与籽类"),
                    ("grain", "谷物/主食"),
                    ("spice", "香料/调料"),
                    ("herb", "香草"),
                    ("oil", "油类"),
                    ("other", "其他"),
                ],
                max_length=50,
                null=True,
                verbose_name="分类",
            ),
        ),
    ]
