# Generated by Django 5.2.1 on 2025-06-10 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_ingredient_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveSmallIntegerField(verbose_name="步骤序号"),
                ),
                ("description", models.TextField(verbose_name="步骤描述")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recipe_steps/",
                        verbose_name="步骤图片 (可选)",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipes.recipe",
                        verbose_name="所属菜谱",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜谱步骤",
                "verbose_name_plural": "菜谱步骤",
                "ordering": ["step_number"],
                "unique_together": {("recipe", "step_number")},
            },
        ),
    ]
