# Generated by Django 5.2.1 on 2025-06-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipestep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="main_image_url",
        ),
        migrations.AddField(
            model_name="recipe",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="recipe_main_images/",
                verbose_name="主图",
            ),
        ),
    ]
