# Generated by Django 5.2.1 on 2025-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_remove_recipe_main_image_url_recipe_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "克 (g)"),
                    ("kg", "千克 (kg)"),
                    ("ml", "毫升 (ml)"),
                    ("l", "升 (l)"),
                    ("tsp", "茶匙 (tsp)"),
                    ("tbsp", "汤匙 (tbsp)"),
                    ("cup", "杯 (cup)"),
                    ("piece", "个/只/颗"),
                    ("slice", "片"),
                    ("pinch", "撮"),
                    ("dash", "少量/几滴"),
                    ("to_taste", "适量"),
                ],
                default="g",
                max_length=10,
                verbose_name="单位",
            ),
        ),
    ]
